# -*- coding: utf-8 -*-
"""Assistente Oficial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lXzlfLxlN-R6msqtDN6CG8__lSHVe92E
"""

import os
import tempfile

from faster_whisper import WhisperModel

from telegram import Update
from telegram.ext import (
    Application,
    MessageHandler,
    ContextTypes,
    filters
)

# tiny = mais leve
# base = mais preciso
model = WhisperModel(
    "tiny",
    device="cpu",
    compute_type="int8"
)

async def transcrever_audio(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE
):
    status = await update.message.reply_text(
        "🎤 Áudio recebido, transcrevendo..."
    )

    caminho_audio = os.path.join(
        tempfile.gettempdir(),
        f"audio_{update.effective_chat.id}.ogg"
    )

    try:
        print("\n=== NOVO ÁUDIO ===")

        # Baixa o áudio do Telegram
        arquivo = await context.bot.get_file(
            update.message.voice.file_id
        )

        await arquivo.download_to_drive(
            custom_path=caminho_audio
        )

        #print(f"Áudio salvo em: {caminho_audio}")

        # Transcrição
        segments, info = model.transcribe(
            caminho_audio,
            language="pt"
        )

        texto = "".join(
            segment.text
            for segment in segments
        ).strip()

        if not texto:
            texto = "Não consegui entender o áudio. Pode repetir?"

        await status.edit_text(
            f"📝 Texto reconhecido:\n\n{texto}"
        )

# Futuramente:
        texto_normalizado = texto.lower()
        texto_normalizado = texto_normalizado.split()
        lista_consulta = ["consulta", "consuta", "consulte", "consultar", "consuntando", "agendar", "marcar", "agendando", "visitar", "verificar", "informação"]
        lista_endereço = ["endereço", "local", "região", "posto", "onde", "fica", "ponto", "rua", "bairro", "perto"]
        lista_domiciliar = ["domiciliar", "casa", "residência", "residencial", "home", "acamado", "locomoção", "vir", "aparamento", "apartamento", "locomover", "lomocover"]


        if any(s in lista_consulta for s in texto_normalizado):
            print("FUNÇÃO_CONSULTA")

        elif any(s in lista_endereço for s in texto_normalizado):
            print("FUNÇÃO_ENDEREÇO")

        elif any( s in lista_domiciliar for s in texto_normalizado):
            print("FUNÇÃO_DOMICILIAR")

        else:
            status.edit_text(
            f"❌ Pode repetir? tente mais devagar e mais alto\n{erro}"
        )

    except Exception as erro:
        print(f"ERRO: {erro}")

        await status.edit_text(
            f"❌ Erro no processamento. Pode repetir?\n{erro}"
        )

    finally:
        if os.path.exists(caminho_audio):
            os.remove(caminho_audio)

def main():
    app = Application.builder().token(TOKEN).build()

    app.add_handler(
        MessageHandler(
            filters.VOICE,
            transcrever_audio
        )
    )

    print("🤖 Bot iniciado!")

if __name__ == "__main__":
    main()